//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mark_body")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub mark_id: String,
    pub ip_source: String,
    pub ip_destination: String,
    pub ip_header_length: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ip_options: Option<String>,
    pub tcp_source: Option<i32>,
    pub tcp_destination: Option<i32>,
    pub tcp_ack: Option<u32>,
    pub tcp_seq: Option<u32>,
    pub tcp_offset: Option<i32>,
    pub tcp_flag: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tcp_options: Option<String>,
    pub is_http: Option<i8>,
    pub http_method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub http_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub http_headers: Option<String>,
    pub create_by: Option<String>,
    pub create_time: Option<DateTime>,
    pub update_by: Option<String>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
